# Frontend Configuration for Porfin WhatsApp Automation Platform
# Version: v1
# Environment: Production
# Last Updated: 2024

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
  labels:
    app: frontend
    component: web
    environment: production
    managed-by: kubernetes
    version: v1
  annotations:
    description: "Frontend environment configuration for production"
    last-updated: "2024-01-01T00:00:00Z"
    update-strategy: "rolling-restart"
    security.porfin.com/reviewed: "true"
    security.porfin.com/compliance: "validated"
    security.porfin.com/last-audit: "2024-01-01"

data:
  # Runtime Environment Configuration
  # Validation: Must be 'production' in production environment
  NODE_ENV: "production"

  # API Endpoints Configuration
  # Validation: Must use HTTPS protocol with valid domain and version path
  NEXT_PUBLIC_API_URL: "https://api.porfin.com/v1"
  
  # WebSocket Configuration
  # Validation: Must use WSS protocol with valid domain and websocket path
  NEXT_PUBLIC_WS_URL: "wss://api.porfin.com/ws"

  # Firebase Configuration
  # Validation: All fields required for proper authentication and service initialization
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "porfin.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "porfin"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "porfin.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "firebase-sender-id"
  NEXT_PUBLIC_FIREBASE_APP_ID: "firebase-app-id"

  # Analytics Configuration
  # Validation: Valid Google Analytics measurement ID
  NEXT_PUBLIC_ANALYTICS_ID: "G-ANALYTICS-ID"

  # Feature Flags and Application Settings
  # Validation: Boolean values for feature toggles
  NEXT_PUBLIC_ENABLE_ANALYTICS: "true"
  NEXT_PUBLIC_ENABLE_ERROR_REPORTING: "true"
  NEXT_PUBLIC_MAINTENANCE_MODE: "false"

  # Regional Settings
  # Validation: Must match supported deployment region
  NEXT_PUBLIC_REGION: "br"
  NEXT_PUBLIC_DEFAULT_LOCALE: "pt-BR"
  NEXT_PUBLIC_DEFAULT_TIMEZONE: "America/Sao_Paulo"

  # Cache and Performance Settings
  # Validation: Numeric values for timing configurations
  NEXT_PUBLIC_CACHE_TTL: "3600"
  NEXT_PUBLIC_API_TIMEOUT: "30000"
  NEXT_PUBLIC_WS_RECONNECT_INTERVAL: "5000"

  # Version Information
  # Validation: Semantic versioning format
  NEXT_PUBLIC_APP_VERSION: "1.0.0"
  NEXT_PUBLIC_API_VERSION: "v1"