apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
    component: cache
    part-of: porfin
    environment: production
data:
  redis.conf: |
    # Memory Management
    # Set max memory to 4GB as per infrastructure requirements
    maxmemory 4gb
    # Use LRU eviction for cache-like behavior
    maxmemory-policy allkeys-lru
    # Enable lazy freeing for better performance
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    # Set max clients based on expected load
    maxclients 10000

    # Persistence Configuration
    # Enable AOF for better durability
    appendonly yes
    appendfsync everysec
    # RDB snapshot settings
    save 900 1
    save 300 10
    save 60 10000
    no-appendfsync-on-rewrite yes
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    # Security Settings
    # Password authentication
    requirepass ${REDIS_PASSWORD}
    protected-mode yes
    # Network security
    tcp-keepalive 300
    bind 0.0.0.0

    # Performance Settings
    # Disable timeouts for long-running operations
    timeout 0
    # Disable cluster mode as per requirements
    cluster-enabled no
    # IO threads for better performance
    io-threads 4
    io-threads-do-reads yes

    # Memory Optimization
    # Enable active memory defragmentation
    activerehashing yes
    active-defrag-threshold-lower 10
    active-defrag-threshold-upper 100
    active-defrag-cycle-min 1
    active-defrag-cycle-max 25
    # Disable huge pages for better memory management
    disable-thp yes

    # Connection Management
    tcp-backlog 511
    tcp-keepalive 300
    maxmemory-samples 10

    # Logging and Monitoring
    loglevel notice
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    latency-monitor-threshold 100

    # Snapshotting Controls
    stop-writes-on-bgsave-error yes
    rdb-save-incremental-fsync yes
    # Compression settings
    rdbcompression yes
    rdbchecksum yes

    # Client Output Buffer Limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60