apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
  labels:
    app: porfin
    component: backend
    environment: production
    managed-by: kubernetes
    version: v1
  annotations:
    kubernetes.io/description: "Contains sensitive configuration for backend service"
    secret-rotation: "30d"
    last-rotated: "2024-01-01T00:00:00Z"  # Update with actual rotation timestamp
type: Opaque
data:
  # Authentication & Security
  SECRET_KEY: "UmFuZG9tMzJDaGFyYWN0ZXJTdHJpbmdGb3JKV1RTZWNyZXQ="  # Random 32-char string for JWT
  BACKUP_ENCRYPTION_KEY: "QmFja3VwRW5jcnlwdGlvbktleUZvclNlY3VyZUJhY2t1cHM="  # Backup encryption key

  # Firebase Authentication
  FIREBASE_PROJECT_ID: "cG9yZmluLXByb2R1Y3Rpb24="  # porfin-production
  FIREBASE_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUVwQUlCQUFLQ0FRRUF4THpFdkxTOHZMeTh2THk4dmVuZDNkM2QzTG5WdVpHVnlMbU52YlE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t"  # Base64 encoded Firebase private key
  FIREBASE_CLIENT_EMAIL: "ZmlyZWJhc2Utc2VydmljZS1hY2NvdW50QHBvcmZpbi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbQ=="  # Firebase service account email

  # Third-Party API Integration
  OPENAI_API_KEY: "c2stWW91ck9wZW5BSUFQSUtleUhlcmU="  # OpenAI API key
  WHATSAPP_BUSINESS_ID: "MTIzNDU2Nzg5MA=="  # WhatsApp Business ID
  WHATSAPP_ACCESS_TOKEN: "RVlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnBjM01pT2lKM2FHRjBjMkZ3Y0M1aWRYTnBibVZ6Y3k1aGNHa3VZMjl0SW4wLg=="  # WhatsApp access token
  WHATSAPP_WEBHOOK_SECRET: "V2hhdHNBcHBXZWJob29rU2VjcmV0S2V5"  # WhatsApp webhook verification

  # Infrastructure Services
  REDIS_PASSWORD: "UmVkaXNTdHJvbmdQYXNzd29yZDEyMyE="  # Redis password
  DATABASE_URL: "cG9zdGdyZXNxbDovL3BvcmZpbkB3cml0ZXIucG9yZmluLXByb2QuaW50ZXJuYWw6NTQzMi9wb3JmaW4="  # Database connection string