apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
    component: monitoring
data:
  prometheus.yml: |
    # Global configuration
    global:
      scrape_interval: 15s     # Default interval for scraping metrics
      evaluation_interval: 15s  # Default interval for evaluating rules
      scrape_timeout: 10s      # Default timeout for scrape requests
      external_labels:
        monitor: 'porfin-prometheus'
        environment: 'production'

    # Rule files for alerts and recording rules
    rule_files:
      - /etc/prometheus/rules/*.rules

    # Scrape configurations for all targets
    scrape_configs:
      # Self-monitoring of Prometheus
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
        metric_relabel_configs:
          - source_labels: ['__name__']
            regex: 'prometheus_.*'
            action: 'keep'

      # Backend service monitoring
      - job_name: 'backend'
        metrics_path: '/metrics'
        scrape_interval: 10s  # More frequent for API monitoring
        scrape_timeout: 5s
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['default']
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_label_app']
            regex: 'porfin'
            action: 'keep'
          - source_labels: ['__meta_kubernetes_pod_label_component']
            regex: 'backend'
            action: 'keep'
          - source_labels: ['__meta_kubernetes_pod_ready']
            regex: 'true'
            action: 'keep'
        metric_relabel_configs:
          # API response time metrics
          - source_labels: ['__name__']
            regex: 'http_request_duration_seconds.*'
            action: 'keep'
          # Message processing metrics
          - source_labels: ['__name__']
            regex: 'message_processing_duration_seconds.*'
            action: 'keep'
          # Database query metrics
          - source_labels: ['__name__']
            regex: 'database_query_duration_seconds.*'
            action: 'keep'

      # WhatsApp service monitoring
      - job_name: 'whatsapp-service'
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['default']
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_label_app']
            regex: 'porfin'
            action: 'keep'
          - source_labels: ['__meta_kubernetes_pod_label_component']
            regex: 'whatsapp'
            action: 'keep'
        metric_relabel_configs:
          # Message handling metrics
          - source_labels: ['__name__']
            regex: 'whatsapp_message_.*'
            action: 'keep'
          # Connection metrics
          - source_labels: ['__name__']
            regex: 'whatsapp_connection_.*'
            action: 'keep'

      # Campaign service monitoring
      - job_name: 'campaign-service'
        metrics_path: '/metrics'
        scrape_interval: 30s
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['default']
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_label_app']
            regex: 'porfin'
            action: 'keep'
          - source_labels: ['__meta_kubernetes_pod_label_component']
            regex: 'campaign'
            action: 'keep'
        metric_relabel_configs:
          # Campaign metrics
          - source_labels: ['__name__']
            regex: 'campaign_.*'
            action: 'keep'
          # Message queue metrics
          - source_labels: ['__name__']
            regex: 'message_queue_.*'
            action: 'keep'

      # Node metrics monitoring
      - job_name: 'node-metrics'
        metrics_path: '/metrics'
        scrape_interval: 30s
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: ['__address__']
            regex: '(.+):(.+)'
            target_label: '__address__'
            replacement: '${1}:9100'
        metric_relabel_configs:
          # System resource metrics
          - source_labels: ['__name__']
            regex: 'node_cpu.*|node_memory.*|node_disk.*|node_network.*'
            action: 'keep'

      # Cache monitoring
      - job_name: 'redis-cache'
        metrics_path: '/metrics'
        scrape_interval: 15s
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['default']
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_label_app']
            regex: 'redis'
            action: 'keep'
        metric_relabel_configs:
          # Cache performance metrics
          - source_labels: ['__name__']
            regex: 'redis_.*'
            action: 'keep'

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']