apiVersion: v1
kind: Secret
metadata:
  name: whatsapp-secrets
  namespace: default
  labels:
    app: whatsapp-service
    component: messaging
    environment: production
    managed-by: terraform
  annotations:
    encryption.kubernetes.io/encrypted: "true"
    rotation.kubernetes.io/schedule: "30d"
    audit.kubernetes.io/level: "Metadata"
data:
  # WhatsApp Business API Credentials
  # Note: Values must be base64 encoded before being added here
  WHATSAPP_BUSINESS_API_TOKEN: <base64_encoded_token>
  WHATSAPP_BUSINESS_PHONE_ID: <base64_encoded_phone_id>
  WHATSAPP_BUSINESS_ACCOUNT_ID: <base64_encoded_account_id>
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: <base64_encoded_verify_token>
  
  # Encryption Keys
  SESSION_ENCRYPTION_KEY: <base64_encoded_encryption_key>
  
  # Redis Authentication
  REDIS_PASSWORD: <base64_encoded_redis_password>
type: Opaque